const tableData = [
  ["Preface", "2. Surah Al-Baqara Starting with Para-2", "Complete book"],
  ["Chapter 1", "3. Surah Al-Imran", ""],
  ["Chapter 2", "4. Surah An-Nisaa", ""],
  ["", "5. Surah Al-Maeda", ""],
  ["", "6. Surah Al-Anaam", ""],
  ["", "7. Surah Al-Araf", ""],
  ["", "12. Surah Yousuf", ""],
  ["", "16. Surah An-Nahl", ""],
  ["", "18. Surah Al-Kahf", ""],
  ["", "26. Surah Ash-Shuara", ""],
  ["", "27. Surah An-Naml", ""],
  ["", "28. Surah Al-Qasas", ""],
  ["", "36. Surah Yaseen", ""],
  ["", "37. Surah Saaffaat", ""],
  ["", "38. Surah Saad", ""],
  ["", "39. Surah Zamar", ""],
  ["", "46. Surah Ahqaaf", ""],
  ["", "47. Surah Muhammad", ""],
  ["", "48. Surah Fatah", ""],
  ["", "50. Surah Qaaf", ""],
  ["", "52. Surah Toor", ""],
  ["", "53. Surah Najm", ""],
  ["", "54. Surah Qamar", ""],
  ["", "55. Surah Rahman", ""],
  ["", "56. Surah Waqia", ""],
  ["", "57. Surah Hadeed", ""],
  ["", "58. Surah Mujadila", ""],
  ["", "59. Surah Hashr", ""],
  ["", "60. Surah Mumtahana", ""],
  ["", "61. Surah Saff", ""],
  ["", "62. Surah Juma", ""],
  ["", "63. Surah Munafiqeen", ""],
  ["", "64. Surah Taghabun", ""],
  ["", "65. Surah Talaq", ""],
  ["", "66. Surah Tehreem", ""],
  ["", "67. Surah Mulk", ""],
  ["", "68. Surah Qalam", ""],
  ["", "69. Surah Al Haaqqa", ""],
  ["", "70. Surah Maarij", ""],
  ["", "71. Surah Nooh", ""],
  ["", "72. Surah Jinn", ""],
  ["", "73. Surah Muzzammil", ""],
  ["", "74. Surah Muddassir", ""],
  ["", "75. Surah Qiyamah", ""],
  ["", "76. Surah Al Insaan", ""],
  ["", "77. Surah Mursalaat", ""],
];

export default tableData;